---
title: "lionfish_model_eemb279"
author: "Leonardo Feitosa"
date: "09/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
```

```{r}
# read in the data
lionfish_tl <- read.csv(here("data", "lionfish_length-frequency_data.csv"), sep = ";") %>% 
  clean_names() %>% 
  select(total_length_tl:august_2015)
```

```{r}
lion_ap_2013 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = april_2013)) +
  labs(x = "",
       y = "",
       title = "April 2013") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```

```{r}
lion_aug_2013 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = august_2013)) +
  labs(x = "",
       y = "",
       title = "August 2013") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```

```{r}
lion_ap_2014 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = april_2014)) +
  labs(x = "",
       y = "",
       title = "April 2014") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```

```{r}
lion_jul_2014 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = july_2014)) +
  labs(x = "",
       y = "",
       title = "July 2014") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```

```{r}
lion_aug_2014 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = august_2014)) +
  labs(x = "",
       y = "",
       title = "August 2014") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```

```{r}
lion_oc_2014 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = october_2014)) +
  labs(x = "",
       y = "",
       title = "October 2014") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```


```{r}
lion_nov_2014 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = november_2014)) +
  labs(x = "",
       y = "",
       title = "November 2014") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```

```{r}
lion_jan_2015 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = january_2015)) +
  labs(x = "",
       y = "",
       title = "January 2015") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```


```{r}
lion_aug_2015 <- ggplot(data = lionfish_tl) +
  geom_col(aes(x = total_length_tl, y = august_2015)) +
  labs(x = "",
       y = "",
       title = "August 2015") +
  theme_bw() +
  theme(axis.title = element_text(color = "black", size = 12),
        axis.text = element_text(color = "black", size = 10))
```


```{r, fig.height=10}
(lion_ap_2013 + lion_aug_2013) /
  (lion_ap_2014 + lion_jul_2014) /
  (lion_aug_2014 + lion_oc_2014) /
  (lion_nov_2014 + lion_jan_2015) /
  (lion_aug_2015) +
  plot_annotation(tag_levels = "A")
```

```{r data wrangling}
# create tibble in long format and separate the original year column into month and year
lionfish_long <- lionfish_tl %>% 
  pivot_longer(cols = april_2013:august_2015,
               names_to = "year",
               values_to = "frequency") %>% 
  separate(year, c("month", "year"), "_")

# sum the frequencies per year
lionfish_sum <- lionfish_long %>% 
  group_by(year, total_length_tl) %>% 
  summarise(freq_sum = sum(frequency))
```

## Parameters for the best fit model used in Johnson & Swenarton (2016)

```{r}
l_inf <- 448 #(mm)
k <- 0.47 # Brody growth coefficient
c <- 0.61 # intensity of seasonal growth oscilation. Varies from 0 to 1, with zero being no seasonality and one extreme seasonality
t_s <- 0.21
t_b <- 0.42
season <- "yes"
var_size_age <- "variable"
```

```{r}
# create timeseries
tset <- seq(from = 0, to = 100, length.out = 10000)

# placeholder variables
N.simu1 <- NaN*tset
N.simu1[1] <- l_inf # this is probably wrong

# create for loop
for(i in 2:length(tset)) { 
  dt <- tset[i] - tset[i - 1] # change in time
  
  N <- N.simu1[i - 1] # placeholder
  
  # calculate population growth
  s_t <- (c * k)/(2 * pi) * sin(pi * (t - t_s)) # formula 3 of the paper
  s_t0 <-(c * k)/(2 * pi) * sin(pi * (t_0 - t_s)) # formula 4 of the paper
  l <- l_inf * (1 - e^(-K * (t - t_0) - s(t) + s(t_0))) # formula 2 of the paper
}
```










 